export default {
  id: "opencode-zen",
  alias: "ocz",
  uiAlias: "ocz",
  display: {
    name: "OpenCode Zen",
    icon: "terminal",
    color: "#E87040",
    textIcon: "OZ",
    website: "https://opencode.ai/auth",
    notice: { apiKeyUrl: "https://opencode.ai/auth" },
  },
  category: "apikey",
  authType: "apikey",
  transport: {
    baseUrl: "https://opencode.ai/zen/v1/chat/completions",
    usage: { url: "https://opencode.ai/zen/v1/usage" },
  },
  transports: [
    {
      format: "openai",
      baseUrl: "https://opencode.ai/zen/v1/chat/completions",
      auth: { combined: true, header: "Authorization", scheme: "bearer" },
    },
    {
      format: "claude",
      baseUrl: "https://opencode.ai/zen/v1/messages",
      auth: { combined: true, header: "x-api-key", scheme: "raw", anthropicVersion: true },
    },
    {
      format: "openai-responses",
      baseUrl: "https://opencode.ai/zen/v1/responses",
      auth: { combined: true, header: "Authorization", scheme: "bearer" },
    },
  ],
  models: [
    { id: "claude-opus-4-8", name: "Claude Opus 4.8", targetFormat: "claude" },
    { id: "claude-opus-4-7", name: "Claude Opus 4.7", targetFormat: "claude" },
    { id: "claude-sonnet-4-6", name: "Claude Sonnet 4.6", targetFormat: "claude" },
    { id: "claude-sonnet-4-5", name: "Claude Sonnet 4.5", targetFormat: "claude" },
    { id: "gpt-6-astra", name: "GPT 6 Astra", targetFormat: "openai-responses" },
    { id: "gpt-5-6-sol", name: "GPT 5.6 Sol", targetFormat: "openai-responses" },
    { id: "gpt-5-6-terra", name: "GPT 5.6 Terra", targetFormat: "openai-responses" },
    { id: "gpt-5-6-luna", name: "GPT 5.6 Luna", targetFormat: "openai-responses" },
    { id: "gpt-5-5", name: "GPT 5.5", targetFormat: "openai-responses" },
    { id: "deepseek-v4-pro", name: "DeepSeek V4 Pro" },
    { id: "deepseek-v4-flash", name: "DeepSeek V4 Flash" },
    { id: "glm-5-2", name: "GLM 5.2" },
    { id: "minimax-m2-7", name: "MiniMax M2.7" },
    { id: "kimi-k2-7-code", name: "Kimi K2.7 Code" },
  ],
  serviceKinds: ["llm"],
  passthroughModels: true,
};
