import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'
type MediaKind = 'image' | 'youtube' | 'html'
type Banner = { id: string; providerId: string; displayName: string; mediaKind: MediaKind; mediaContent: string; href: string; position: number; enabled: boolean }
const corsHeaders = { 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'authorization, content-type, apikey, x-client-info', 'Access-Control-Allow-Methods': 'GET, POST, DELETE, OPTIONS' }
const json = (body: unknown, status = 200) => Response.json(body, { status, headers: corsHeaders })
const SLUG = /^[a-z0-9][a-z0-9-]{0,62}$/
function httpsUrl(v: unknown, f: string) { if (typeof v !== 'string') throw new Error(`${f} is required`); try { const u = new URL(v); if (u.protocol !== 'https:') throw new Error(); return u.toString() } catch { throw new Error(`${f} must be an https URL`) } }
function youtubeId(v: unknown) { const url = httpsUrl(v, 'mediaContent'); const p = new URL(url); const id = p.hostname === 'youtu.be' ? p.pathname.slice(1) : ['youtube.com','www.youtube.com','m.youtube.com'].includes(p.hostname) ? p.searchParams.get('v') ?? p.pathname.match(/^\/embed\/([\w-]+)/)?.[1] : null; if (!id || !/^[\w-]{11}$/.test(id)) throw new Error('mediaContent must be a supported YouTube URL'); return id }
function bannerFrom(b: unknown): Banner { if (!b || typeof b !== 'object') throw new Error('provider is required'); const r = b as Record<string, unknown>; const id = typeof r.id === 'string' ? r.id.trim() : ''; const pid = typeof r.providerId === 'string' ? r.providerId.trim() : ''; const dn = typeof r.displayName === 'string' ? r.displayName.trim() : ''; const mk = r.mediaKind as string | undefined; const mc = r.mediaContent as string | undefined; const href = r.href != null ? String(r.href).trim() : ''; const pos = r.position != null ? Number(r.position) : 999; if (!SLUG.test(id)) throw new Error('id must be lowercase letters, numbers, or hyphens'); if (!SLUG.test(pid)) throw new Error('providerId is required — the provider card this banner shows on'); if (!dn || dn.length > 120) throw new Error('displayName must be 1-120 characters'); if (!mk || !['image','youtube','html'].includes(String(mk))) throw new Error('mediaKind must be image, youtube, or html'); if (!mc || !String(mc).trim()) throw new Error('mediaContent is required'); if (String(mc).length > 100000) throw new Error('mediaContent exceeds 100 KB'); if (href && !/^https:\/\//.test(href)) throw new Error('href must be https or empty'); if (!Number.isInteger(pos) || pos < 0 || pos > 999) throw new Error('position must be 0-999'); const o: Banner = { id, providerId: pid, displayName: dn, mediaKind: mk as MediaKind, mediaContent: '', href, position: pos, enabled: r.enabled !== false }; if (mk === 'image') o.mediaContent = httpsUrl(mc,'mediaContent'); else if (mk === 'youtube') o.mediaContent = youtubeId(mc); else o.mediaContent = String(mc); return o }
function toRow(b: Banner) { return { id: b.id, provider_id: b.providerId, display_name: b.displayName, media_kind: b.mediaKind, media_content: b.mediaContent, href: b.href || '', position: b.position, enabled: b.enabled } }
function toBanner(row: Record<string, unknown>): Banner { return { id: String(row.id), providerId: String(row.provider_id ?? ''), displayName: String(row.display_name), mediaKind: String(row.media_kind) as MediaKind, mediaContent: String(row.media_content), href: String(row.href ?? ''), position: Number(row.position ?? 999), enabled: row.enabled !== false } }
const COLS = 'id,provider_id,display_name,media_kind,media_content,href,position,enabled'
Deno.serve(async (req) => { if (req.method === 'OPTIONS') return new Response(null, { headers: corsHeaders }); const url = new URL(req.url); const admin = createClient(Deno.env.get('SUPABASE_URL')!, Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!, { auth: { persistSession: false } }); if (req.method === 'GET') { let q = admin.from('embedding_providers').select(COLS).eq('enabled', true).order('position', { ascending: true }).order('id', { ascending: true }); const id = url.searchParams.get('id'); const pid = url.searchParams.get('provider_id'); if (id) q = q.eq('id', id); if (pid) q = q.eq('provider_id', pid); const { data, error } = await q; if (error) return json({ error: error.message }, 500); return json({ providers: (data ?? []).map(toBanner) }) } const auth = req.headers.get('Authorization'); if (!auth?.startsWith('Bearer ')) return json({ error: 'missing Authorization: Bearer <supabase auth JWT>' }, 401); const tok = auth.slice(7); const { data: { user }, error: e } = await admin.auth.getUser(tok); if (e || !user) return json({ error: 'invalid authentication' }, 401); if (req.method === 'POST') { try { const { provider } = await req.json(); const b = bannerFrom(provider); const { data, error } = await admin.from('embedding_providers').upsert(toRow(b)).select().single(); if (error) return json({ error: error.message }, 400); return json({ provider: toBanner(data) }) } catch (err) { return json({ error: (err as Error).message }, 400) } } if (req.method === 'DELETE') { const id = url.searchParams.get('id'); if (!id) return json({ error: 'id is required' }, 400); const { error } = await admin.from('embedding_providers').delete().eq('id', id); if (error) return json({ error: error.message }, 400); return json({ deleted: id }) } return json({ error: 'method not allowed' }, 405) })
